# In this worflow we are using needs to force the jobs run in a sequence and upload/download artifacts to make the file available to next job.

name: Needs and Artifacts in Github
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checking-out the respo
              uses: actions/checkout@v5
            - name: Installing cowsay
              run: sudo apt-get install cowsay -y
            - name: Executing cowsay commands
              run: cowsay -f dragon "Run for the cover, I am a Dragon.... RWAR" >> dragon.txt
            - name: uploading dragon file
              id: upload
              uses: actions/upload-artifact@v4   ## uploading artifacts
              with:
                name: dragon.txt-file
                path: dragon.txt
                if-no-files-found: error
                retention-days: 1
            - name: Display all outputs from upload-artifcats
              run: |
                echo "Artifact ID: ${{ steps.upload.outputs.artifact-id }}"
                echo "Artifact URL: ${{ steps.upload.outputs.artifact-url }}"
                echo "Download URL: ${{ steps.upload.outputs.download-url }}"             
            
    second-job:
        runs-on: ubuntu-latest
        needs: first-job            ## allows second-job to run after successful completation of first-job
        steps:
           - name: sleep for 5 sec
             run: sleep 5
           - name: Downloading dragon file    ## downloading the artifacts 
             uses: actions/download-artifact@v5
             with:
              name: dragon.txt-file
           - name: testing the file
             run: cat dragon.txt
            

        