# To demonstrate we will login to Docker and launch docker container
name: Exploring variables and secrets
on: push
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            # - name: Docker Build
            #   run: docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USRNAME}}/${{env.IMAGE_NAME}}:latest
            - name: Docker login
              run: docker login --username=${{vars.DOCKER_USRNAME}} --password=${{secrets.DOCKER_PASSWORD}}
    #         - name: Docker Publish
    #           run: docker push ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: docker
    #     steps:
    #         - name: Docker run
    #           run: docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USRNAME}}/${{env.IMAGE_NAME}}:latest